services:
  workbench:
    image: carpentries/workbench-docker:v0.2.2
    environment:
      WORKBENCH_PROFILE: "local"
    ports:
      - 127.0.0.1:4321:4321
    entrypoint: ["/bin/sh"]
    command:
      - -c
      - Rscript -e 'sandpaper::serve("/home/rstudio/lessons/rse_introductory_git_course", host="0.0.0.0")'
    volumes:
      - ./:/home/rstudio/lessons/rse_introductory_git_course
